### ISSUE TITLE
this.allowedMethods.patch = true

### ISSUE THREAD

**Issue by melvincarvalho** [solid/solid.js#35]
I'm getting an error logging in:

```Javascript
    Uncaught TypeError: Cannot read property 'allowedMethods' of undefined
    parseAllowedMethods @ solid.js:603
    SolidResponse @ solid.js:402
    http.onload @ solid.js:709
```

Should `this` be removed from the dist file?

https://github.com/solid/solid.js/blob/156f3e7da97521f05f7f063e8c82da7417d16f6b/dist/solid.js#L603

**Comment by dmitrizagidulin** [comment]
Should be fixed in PR #33. (Merging shortly)

**Comment by dmitrizagidulin** [comment]
@melvincarvalho - Ok, #33 has been merged, try it out with the latest version.

**Comment by dmitrizagidulin** [comment]
Talked to melvin, seems to be working. Closing.
