### ISSUE TITLE
Patch example has empty URI in 

### ISSUE THREAD

**Issue by timbl** [solid/solid.js#4]
Firstly you need a non-empty URI for the subject.
Secondly, you can use pass a string to mean a literal.  
Note, the $rdf.lit("Hello")).toNT() is wrong, as it generates a canonical NT string not an object, whcih would end up making a string object with extra quotes around it.

```
var oldTitle = $rdf.st($rdf.sym(''), $rdf.sym('http://purl.org/dc/terms/title'), $rdf.lit("First post")).toNT();

var newTitle = $rdf.st($rdf.sym(''), $rdf.sym('http://purl.org/dc/terms/title'), $rdf.lit("Hello")).toNT();
```

should be more like

```
var post = rdf.sym(''https://example.org/blog/hello-world#post1");

var oldTitle = $rdf.st(post, $rdf.sym('http://purl.org/dc/terms/title'),  "First post");
var newTitle = $rdf.st(post, $rdf.sym('http://purl.org/dc/terms/title'), "Hello");

var toDel = [ oldTtitle ];
var toIns = [ newTitle ];
Solid.web.patch(post.doc(), toDel, toIns).then(function(meta){
    console.log(meta.xhr.status); // HTTP 200 (OK)
}).catch(function(err) {
   console.log(err); // error object
   ... 
});

```

**Comment by deiu** [comment]
You're right about the URI.

On the other hand, the reason why I didn't pass the object to the `patch()` function is that I am trying to make the Solid.js agnostic to any RDF library, so as not to force it on the developer. Basically keep the Solid.js library decoupled from any RDF library the developer might be using.
