### ISSUE TITLE
Avoid duplication of links in the profile object.

### ISSUE THREAD

**Issue by deiu** [solid/solid.js#50]
For example, when building the list of related profiles, solid.js should avoid append the same URI to the array. Basically, don't append to array if the same value already exists in the array. I think this behavior currently applies to all the links exposed in a profile document.

```
relatedProfiles: Object
  preferences: Array[2]
    0: "https://deiu.me/Preferences/prefs"
    1: "https://deiu.me/Preferences/prefs"
```

**Comment by dmitrizagidulin** [comment]
Fixed in PR #55, closing.
