### ISSUE TITLE
Publishing on npm?

### ISSUE THREAD

**Issue by nicola** [solid/solid.js#59]
Most of the code I write is really node first, so I generally use npm for everything, even installing packages. Although as of now I have installed it via git (`npm install solid/solid.js`) I am wondering if we should publish this on the npm registry

**Comment by dmitrizagidulin** [comment]
Ah, yeah, not a bad idea. I'll do that shortly.

**Comment by dmitrizagidulin** [comment]
Boo, somebody took the `solid` package name already :) https://www.npmjs.com/package/solid-node

**Comment by dmitrizagidulin** [comment]
What should we publish it as? `solid-client` or `solid.js`?

**Comment by nicola** [comment]
If I am not wrong I asked the owner of `solid` if they could give that to us, otherwise solid-client sounds good to me

**Comment by deiu** [comment]
:+1: to `solid-client`

**Comment by dmitrizagidulin** [comment]
Ok, published on npm: https://www.npmjs.com/package/solid-client

Closing.
