### ISSUE TITLE
getParsedGraph error tabulator is not defined

### ISSUE THREAD

**Issue by rhiaro** [solid/solid.js#81]
Copied the example from the readme:

```
solid.web.getParsedGraph(resource).then(
          function(response) {
            console.log(response.statementsMatching(undefined, RDF('type'), LDP('Resource')))
          }
        )
```

Error: `tabulator is not defined rdflib-0.5.0.min.js:119`

Pending further investigation by @dmitrizagidulin

**Comment by dmitrizagidulin** [comment]
Upstream issue opened, [rdflib.js#124](https://github.com/linkeddata/rdflib.js/issues/124)

**Comment by dmitrizagidulin** [comment]
@rhiaro - while we're sorting out the upstream RDFLib.js fix, the new equivalent usage is described at https://github.com/solid/solid.js#fetching-a-parsed-graph

**Comment by dmitrizagidulin** [comment]
Closing, I'm pretty sure this has been fixed. Please re-open if not.
